### ISSUE TITLE
No data on DB

### ISSUE THREAD

**Issue by ofuochi** [lancetharper/140dev#1]
I followed through your instruction (http://140dev.com/free-twitter-api-source-code-library/twitter-database-server/install/) line by line and step by step. Nothing shows up on my data base at first but after a long long wait, somethings data shows up (but just a few).

I tried to use the display plugin as instructed (http://140dev.com/free-twitter-api-source-code-library/twitter-display/) to display the tweets on a webpage but NOTHING!

Please what am I doing wrong? Am really desperate as this framework is a core to my Project

**Comment by lancetharper** [comment]
140 dev and those instructions were not created by me. I was just using them in this project for a class.
